version: '3.7'
services:
  db-fba:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db-fba-volume:/var/lib/mysql
  web-fba:
    image: web-fba:1.0
    build: ./web-fba
    container_name: fba-web
    volumes:
       - "./static:/app/static/:ro"
       - "./budget_app:/app/budget_app/:ro"
       - "./FamilyBudget:/app/FamilyBudget/:ro"
       - "./manage.py:/app/:ro"
       - "./requirements.txt:/app/:ro"
    depends_on:
      - db-fba
  nginx-fba:
    image: nginx-fba:1.19
    build: ./nginx
    container_name: fba-nginx
    volumes_from:
       -web-fba:ro
    ports:
      - 8800:80
    networks:
      - lb-fba-network
    depends_on:
      - web-fba
networks:
  lb-fba-network:
    name: lb-fba-network
    external: false
volumes:
  db-fba-volume: