# Generated by Django 3.2 on 2022-09-20 14:05

import budget_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Budget',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[budget_app.models.validate_min_cashflow, budget_app.models.validate_max_cashflow])),
                ('text', models.TextField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('w', 'Salary'), ('b', 'Bonus'), ('s', 'Scholarship'), ('p', 'Pension'), ('fb', 'Family Benefits'), ('f', 'Franchise'), ('i', 'Interest'), ('ap', 'Affiliate Programs'), ('iv', 'Investment'), ('d', 'Dividend'), ('l', 'Lease'), ('sm', 'Stock Market'), ('fn', 'Funds'), ('de', 'Deposits'), ('pm', 'Pocket Money'), ('o', 'Other')], default='o', max_length=2)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='budget_app.budget')),
            ],
            options={
                'ordering': ['-value'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[budget_app.models.validate_min_cashflow, budget_app.models.validate_max_cashflow])),
                ('text', models.TextField(blank=True, max_length=255, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='budget_app.budget')),
                ('category', models.ForeignKey(on_delete=models.SET(budget_app.models.get_sentinel_expense_category), to='budget_app.expensecategory')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning_budgets', to='budget_app.profile'),
        ),
        migrations.AddField(
            model_name='budget',
            name='shared',
            field=models.ManyToManyField(blank=True, related_name='sharing', to='budget_app.Profile'),
        ),
    ]
