name: Develop Workflow
on:
  push:
    branches: [develop]
jobs:
  prepare:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Preparation
        run: echo "💡 The ${{ github.repository }} is beeing prepared for develop."
  tests:
    uses: ./.github/workflows/tests.yaml
    with:
      break_on_linter: false
  check:
    name: Run check
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Run Django check
        run: python manage.py check
