name: Develop Workflow
on: 
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: Setup python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      
      - name: Flake8
        run: flake8 . --exclude .git,.venv --count --show-source --statistics --max-line-length=127
      - name: Run Django Tests
        run: python manage.py test