name: Develop Workflow
on:
  push:
    branches: [develop]
jobs:
  # prepare:
  #   runs-on: ubuntu-latest
  #   continue-on-error: true
  #   steps:
  #     - name: Preparation
  #       run: echo "💡 The ${{ github.repository }} is beeing prepared for develop."
  tests:
    name: Test
    uses: ./.github/workflows/tests.yaml
    with:
      break_on_linter: false
  check:
    name: Run check
    runs-on: ubuntu-latest
    needs: tests
    continue-on-error: false
    steps:
      - name: Run Django check
        run: ls -all ; python manage.py check
        
